server:
  port: 9192
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
  client:
    registry-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/